# Generated by Django 4.2.30 on 2026-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this user has access to.', related_name='members', to='projects.project'),
        ),
    ]
