# Generated by Django 4.2.30 on 2026-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_id', models.CharField(max_length=255, unique=True)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
