# Generated by Django 4.2.30 on 2026-07-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('kobo_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this submission belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='projects.project'),
        ),
    ]
