# Generated by Django 4.2.30 on 2026-07-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo_integration', '0002_record_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='is_locally_updated',
            field=models.BooleanField(default=False),
        ),
    ]
