# Generated by Django 4.2.30 on 2026-07-16 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_admins',
            field=models.ManyToManyField(blank=True, help_text="Admin users responsible for managing this project's users.", limit_choices_to={'groups__name': 'Admin'}, related_name='administered_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
