# Generated by Django 4.2.30 on 2026-07-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='schema_json',
            field=models.JSONField(blank=True, default=dict, help_text='The parsed schema representation of the XLSForm.'),
        ),
        migrations.AddField(
            model_name='project',
            name='xlsform',
            field=models.FileField(blank=True, help_text='Upload the XLSForm (.xlsx) file to enable dynamic forms and label translation.', null=True, upload_to='xlsforms/'),
        ),
    ]
